name: 'workflows日志自动清理'

on:
  schedule:
    - cron: '0 0 */2 * *'
  workflow_dispatch:

jobs:
  del_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: yxnwh/delete-workflow-runs@main
        with:
          retain_days: 3
          keep_minimum_runs: 4
